[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/app.com
command=php /var/www/app.com/artisan queue:work redis --sleep=3 --tries=3 --timeout=90 --max-jobs=1000 --max-time=3600
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=3600
stopsignal=QUIT
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/var/www/app.com/storage/logs/worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
environment=APP_ENV="production"
